# Generated by Django 3.1.4 on 2021-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(null=True, to='Quiz.Category'),
        ),
    ]
