# Generated by Django 3.1.4 on 2021-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20210104_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.AddField(
            model_name='category',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
