# Generated by Django 3.1.4 on 2021-01-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20210104_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_taken',
            field=models.CharField(default='0.0', max_length=500),
        ),
    ]
